//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snipping_OCR {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snipping_OCR.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Exit software 的本地化字符串。
        /// </summary>
        internal static string ExitSoftware {
            get {
                return ResourceManager.GetString("ExitSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Mode 的本地化字符串。
        /// </summary>
        internal static string FocusMode {
            get {
                return ResourceManager.GetString("FocusMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey registration failed, you can still use other methods to Hotkey registration failed, you can still use other methods to perform OCR. 的本地化字符串。
        /// </summary>
        internal static string HotkeyRegistrationFailed {
            get {
                return ResourceManager.GetString("HotkeyRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APP ID 的本地化字符串。
        /// </summary>
        internal static string labAPPID {
            get {
                return ResourceManager.GetString("labAPPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secret 的本地化字符串。
        /// </summary>
        internal static string labSecret {
            get {
                return ResourceManager.GetString("labSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recognize clipboard 的本地化字符串。
        /// </summary>
        internal static string RecognizeClipboard {
            get {
                return ResourceManager.GetString("RecognizeClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Settings 的本地化字符串。
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snipping OCR 的本地化字符串。
        /// </summary>
        internal static string ScreenOCR {
            get {
                return ResourceManager.GetString("ScreenOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the APPID and Secret. 的本地化字符串。
        /// </summary>
        internal static string SettingsTips {
            get {
                return ResourceManager.GetString("SettingsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show interface 的本地化字符串。
        /// </summary>
        internal static string ShowInterface {
            get {
                return ResourceManager.GetString("ShowInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start screenshot 的本地化字符串。
        /// </summary>
        internal static string StartScreenshot {
            get {
                return ResourceManager.GetString("StartScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn Off 的本地化字符串。
        /// </summary>
        internal static string TF {
            get {
                return ResourceManager.GetString("TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn On 的本地化字符串。
        /// </summary>
        internal static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate selected 的本地化字符串。
        /// </summary>
        internal static string TranslateSelected {
            get {
                return ResourceManager.GetString("TranslateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate Settings 的本地化字符串。
        /// </summary>
        internal static string TranslateSettings {
            get {
                return ResourceManager.GetString("TranslateSettings", resourceCulture);
            }
        }
    }
}
